package com.demo.entities;
// Generated Nov 21, 2021, 7:14:54 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountSetting generated by hbm2java
 */
@Entity
@Table(name = "account_setting", catalog = "music_app")
public class AccountSetting implements java.io.Serializable {

	private Integer id;
	private Account account;
	private boolean newFollower;
	private boolean newComment;
	private boolean newPackage;
	private boolean specialDiscount;

	public AccountSetting() {
	}

	public AccountSetting(Account account, boolean newFollower, boolean newComment, boolean newPackage,
			boolean specialDiscount) {
		this.account = account;
		this.newFollower = newFollower;
		this.newComment = newComment;
		this.newPackage = newPackage;
		this.specialDiscount = specialDiscount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "new_follower", nullable = false)
	public boolean isNewFollower() {
		return this.newFollower;
	}

	public void setNewFollower(boolean newFollower) {
		this.newFollower = newFollower;
	}

	@Column(name = "new_comment", nullable = false)
	public boolean isNewComment() {
		return this.newComment;
	}

	public void setNewComment(boolean newComment) {
		this.newComment = newComment;
	}

	@Column(name = "new_package", nullable = false)
	public boolean isNewPackage() {
		return this.newPackage;
	}

	public void setNewPackage(boolean newPackage) {
		this.newPackage = newPackage;
	}

	@Column(name = "special_discount", nullable = false)
	public boolean isSpecialDiscount() {
		return this.specialDiscount;
	}

	public void setSpecialDiscount(boolean specialDiscount) {
		this.specialDiscount = specialDiscount;
	}

}
