package com.demo.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountSetting generated by hbm2java
 */
@Entity
@Table(name = "account_setting", catalog = "music_app")
public class AccountSetting implements java.io.Serializable {

	private Integer id;
	private Account account;
	private boolean newFollower;
	private boolean packageOutDate;

	public AccountSetting() {
	}

	public AccountSetting(Account account, boolean newFollower, boolean packageOutDate) {
		this.account = account;
		this.newFollower = newFollower;
		this.packageOutDate = packageOutDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "new_follower", nullable = false)
	public boolean isNewFollower() {
		return this.newFollower;
	}

	public void setNewFollower(boolean newFollower) {
		this.newFollower = newFollower;
	}

	@Column(name = "package_out_date", nullable = false)
	public boolean isPackageOutDate() {
		return this.packageOutDate;
	}

	public void setPackageOutDate(boolean packageOutDate) {
		this.packageOutDate = packageOutDate;
	}

}
