package com.demo.entities;
// Generated Nov 21, 2021, 7:03:46 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountRoleId generated by hbm2java
 */
@Embeddable
public class AccountRoleId implements java.io.Serializable {

	private int accountId;
	private int roleId;

	public AccountRoleId() {
	}

	public AccountRoleId(int accountId, int roleId) {
		this.accountId = accountId;
		this.roleId = roleId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountRoleId))
			return false;
		AccountRoleId castOther = (AccountRoleId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
