package com.demo.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentId generated by hbm2java
 */
@Embeddable
public class CommentId implements java.io.Serializable {

	private int accountId;
	private int trackId;

	public CommentId() {
	}

	public CommentId(int accountId, int trackId) {
		this.accountId = accountId;
		this.trackId = trackId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "track_id", nullable = false)
	public int getTrackId() {
		return this.trackId;
	}

	public void setTrackId(int trackId) {
		this.trackId = trackId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentId))
			return false;
		CommentId castOther = (CommentId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getTrackId() == castOther.getTrackId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getTrackId();
		return result;
	}

}
