package com.demo.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genres generated by hbm2java
 */
@Entity
@Table(name = "genres", catalog = "music_app")
public class Genres implements java.io.Serializable {

	private Integer id;
	private String name;
	private String thumbnail;
	private Set<Track> tracks = new HashSet<Track>(0);

	public Genres() {
	}

	public Genres(String name, String thumbnail) {
		this.name = name;
		this.thumbnail = thumbnail;
	}

	public Genres(String name, String thumbnail, Set<Track> tracks) {
		this.name = name;
		this.thumbnail = thumbnail;
		this.tracks = tracks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "thumbnail", nullable = false, length = 250)
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genres")
	public Set<Track> getTracks() {
		return this.tracks;
	}

	public void setTracks(Set<Track> tracks) {
		this.tracks = tracks;
	}

}
