package com.demo.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PackageInfoId generated by hbm2java
 */
@Embeddable
public class PackageInfoId implements java.io.Serializable {

	private int packageId;
	private int accountId;

	public PackageInfoId() {
	}

	public PackageInfoId(int packageId, int accountId) {
		this.packageId = packageId;
		this.accountId = accountId;
	}

	@Column(name = "package_id", nullable = false)
	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PackageInfoId))
			return false;
		PackageInfoId castOther = (PackageInfoId) other;

		return (this.getPackageId() == castOther.getPackageId()) && (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPackageId();
		result = 37 * result + this.getAccountId();
		return result;
	}

}
