package com.demo.entities;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * PackageInfo generated by hbm2java
 */
@Entity
@Table(name = "package_info", catalog = "music_app")
public class PackageInfo implements java.io.Serializable {

	private PackageInfoId id;
	private Account account;
	private ServicePackage servicePackage;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date purchaseDate;
	
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date expirationDate;

	public PackageInfo() {
	}

	public PackageInfo(PackageInfoId id, Account account, ServicePackage servicePackage, Date purchaseDate,
			Date expirationDate) {
		this.id = id;
		this.account = account;
		this.servicePackage = servicePackage;
		this.purchaseDate = purchaseDate;
		this.expirationDate = expirationDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)),
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)) })
	public PackageInfoId getId() {
		return this.id;
	}

	public void setId(PackageInfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_id", nullable = false, insertable = false, updatable = false)
	public ServicePackage getServicePackage() {
		return this.servicePackage;
	}

	public void setServicePackage(ServicePackage servicePackage) {
		this.servicePackage = servicePackage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "purchase_date", nullable = false, length = 10)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", nullable = false, length = 10)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

}