package com.demo.entities;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlaylistTrack generated by hbm2java
 */
@Entity
@Table(name = "playlist_track", catalog = "music_app")
public class PlaylistTrack implements java.io.Serializable {

	private PlaylistTrackId id;
	private Playlist playlist;
	private Track track;

	public PlaylistTrack() {
	}

	public PlaylistTrack(PlaylistTrackId id, Playlist playlist, Track track) {
		this.id = id;
		this.playlist = playlist;
		this.track = track;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "playlistId", column = @Column(name = "playlist_id", nullable = false)),
			@AttributeOverride(name = "trackId", column = @Column(name = "track_id", nullable = false)) })
	public PlaylistTrackId getId() {
		return this.id;
	}

	public void setId(PlaylistTrackId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "playlist_id", nullable = false, insertable = false, updatable = false)
	public Playlist getPlaylist() {
		return this.playlist;
	}

	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "track_id", nullable = false, insertable = false, updatable = false)
	public Track getTrack() {
		return this.track;
	}

	public void setTrack(Track track) {
		this.track = track;
	}

}
