package com.demo.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlaylistTrackId generated by hbm2java
 */
@Embeddable
public class PlaylistTrackId implements java.io.Serializable {

	private int playlistId;
	private int trackId;

	public PlaylistTrackId() {
	}

	public PlaylistTrackId(int playlistId, int trackId) {
		this.playlistId = playlistId;
		this.trackId = trackId;
	}

	@Column(name = "playlist_id", nullable = false)
	public int getPlaylistId() {
		return this.playlistId;
	}

	public void setPlaylistId(int playlistId) {
		this.playlistId = playlistId;
	}

	@Column(name = "track_id", nullable = false)
	public int getTrackId() {
		return this.trackId;
	}

	public void setTrackId(int trackId) {
		this.trackId = trackId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlaylistTrackId))
			return false;
		PlaylistTrackId castOther = (PlaylistTrackId) other;

		return (this.getPlaylistId() == castOther.getPlaylistId()) && (this.getTrackId() == castOther.getTrackId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlaylistId();
		result = 37 * result + this.getTrackId();
		return result;
	}

}
