package com.demo.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServicePackage generated by hbm2java
 */
@Entity
@Table(name = "service_package", catalog = "music_app")
public class ServicePackage implements java.io.Serializable {

	private Integer id;
	private String name;
	private double price;
	private int duration;
	private boolean status;
	private String description;
	private boolean isDelete;
	private Set<PackageInfo> packageInfos = new HashSet<PackageInfo>(0);

	public ServicePackage() {
	}

	public ServicePackage(String name, double price, int duration, boolean status, String description,
			boolean isDelete) {
		this.name = name;
		this.price = price;
		this.duration = duration;
		this.status = status;
		this.description = description;
		this.isDelete = isDelete;
	}

	public ServicePackage(String name, double price, int duration, boolean status, String description, boolean isDelete,
			Set<PackageInfo> packageInfos) {
		this.name = name;
		this.price = price;
		this.duration = duration;
		this.status = status;
		this.description = description;
		this.isDelete = isDelete;
		this.packageInfos = packageInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_delete", nullable = false)
	public boolean isIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicePackage")
	public Set<PackageInfo> getPackageInfos() {
		return this.packageInfos;
	}

	public void setPackageInfos(Set<PackageInfo> packageInfos) {
		this.packageInfos = packageInfos;
	}

}
