package com.demo.entities;
// Generated Nov 21, 2021, 7:14:54 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Setting generated by hbm2java
 */
@Entity
@Table(name = "setting", catalog = "music_app")
public class Setting implements java.io.Serializable {

	private Integer id;
	private Banner banner;
	private int showTopChart;

	public Setting() {
	}

	public Setting(Banner banner, int showTopChart) {
		this.banner = banner;
		this.showTopChart = showTopChart;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banner_id", nullable = false)
	public Banner getBanner() {
		return this.banner;
	}

	public void setBanner(Banner banner) {
		this.banner = banner;
	}

	@Column(name = "show_top_chart", nullable = false)
	public int getShowTopChart() {
		return this.showTopChart;
	}

	public void setShowTopChart(int showTopChart) {
		this.showTopChart = showTopChart;
	}

}
